/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MemoryDialog: typeof import('./src/components/MemoryDialog.vue')['default']
    NodePalette: typeof import('./src/components/NodePalette.vue')['default']
    PatchCanvas: typeof import('./src/components/PatchCanvas.vue')['default']
    PatchNode: typeof import('./src/components/PatchNode.vue')['default']
    PatchWire: typeof import('./src/components/PatchWire.vue')['default']
    ProgramBrowser: typeof import('./src/components/ProgramBrowser.vue')['default']
    ProgramBrowserNode: typeof import('./src/components/ProgramBrowserNode.vue')['default']
  }
}
