/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RhythmHadamard: typeof import('./src/components/RhythmHadamard.vue')['default']
    RhythmIV: typeof import('./src/components/RhythmIV.vue')['default']
    RhythmSelector: typeof import('./src/components/RhythmSelector.vue')['default']
  }
}
